[INFO              ] Logger: Record log in /storage/emulated/0/kivy/packer/.kivy/logs/kivy_17-07-06_0.txt
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.2 (default, Mar 20 2016, 23:30:13) 
[GCC 4.8]
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 6, in <module>
[WARNING           ] stderr:     os.chdir(path)
[WARNING           ] stderr: OSError: [Errno 2] No such file or directory: 'assets/images/ground/'
